export const FETCH_WEATHER = "COMMAND/FETCH_WEATHER_FOR_LAT_LNG";
export const API_ERROR = "EVENT/API_ERROR_RECEIVED";
export const WEATHER_DATA_RECEIVED = "EVENT/WEATHER_DATA_RECEIVED";
export const WEATHER_ID_RECEIVED = "EVENT/WEATHER_ID_RECEIVED";

export const FETCH_DRONE_LOCATIONS = "FETCH_DRONE_LOCATIONS";
export const FETCH_DRONE_LOCATIONS_SUCCESS = "FETCH_DRONE_LOCATIONS_SUCCESS";
export const FETCH_DRONE_LOCATIONS_FAILURE = "FETCH_DRONE_LOCATIONS_FAILURE";